### PR TITLE
API: new endpoint '/composes/{id}/metadata'

### PR DESCRIPTION
**Pull request by achilleas-k**
Added metadata API endpoint (composes/id/metadata) that returns the information from the equivalent endpoint in osbuild-composer:
- packages: full list of package NEVRAs included in the image.
- ostree_commit: the ID/hash of the ostree commit that was created (for edge types only)

Depends on osbuild/osbuild-composer#1490

### CODE REVIEW

**Comment by achilleas-k** [comment]
API integration test script calls the metadata endpoint to verify package list at the end of the builds.
I've updated the osbuild-composer commit in the deploy script to match current main after the composer PR was merged.

**Comment by teg** [comment]
We probably need to deploy the composer one before merging this or we will have a bad time. Might also want to update the osbuild version for the ro /sys patch

**Comment by achilleas-k** [comment]
Blocked by https://github.com/osbuild/image-builder-packer/pull/18

**Comment by teg** [comment]
The osbuild-composer repos moved (when we moved to gitlab), so need to update the URL. I did the same in the packer repo.

**Comment by ondrejbudai** [comment]
This is no longer needed, we merged https://github.com/osbuild/osbuild-composer/commit/419ac4c7699b72cd4ca5fc89c8f46bd579baf06c yesterday to remove the extra path segment, just use the latest `main` commit.

**Comment by Gundersanne** [comment]
> This is no longer needed, we merged [osbuild/osbuild-composer@419ac4c](https://github.com/osbuild/osbuild-composer/commit/419ac4c7699b72cd4ca5fc89c8f46bd579baf06c) yesterday to remove the extra path segment, just use the latest `main` commit.

still needed to change `osbuild-composer-repos.s3-website.us-east-2.amazonaws.com` to `osbuild-composer-repos.s3.amazonaws.com` no?

**Review by teg — APPROVED** [review]
Nice! Thanks!

**Pull request merged**
