### PR TITLE
v1/api: Change empty structs to nil for blueprint export

### PR DESCRIPTION
**Pull request by avitova**
This is a followup related to [this thread](https://github.com/osbuild/image-builder/pull/1264#discussion_r1684287363).
Let me know if that's what you had in mind.

### CODE REVIEW

**Comment by ezr-ondrej** [comment]
Nice! I :orange_heart: the follow-up!
One idea I had now: are we testing the metadata inserting anywhere? (I didn't check, figured I ask first) :)

**Review by lzap — APPROVED** [review]

**Review by ezr-ondrej — APPROVED** [review]
This is great, thanks :+1:

**Comment by ezr-ondrej** [comment]
That sounds bit weird to me :) I think it'd be fine to test it on the database layer.
Send it through handler and fetch from DB :)
Or just test it on the DB level only in the DB tests.

**Comment by avitova** [comment]
Sure, I will do a followup of a followup. :)

**Pull request merged**
