### PR TITLE
internal: update api specs

### PR DESCRIPTION
**Pull request by schutzbot**
Client API specs update.

### CODE REVIEW

**Review by lzap — APPROVED** [review]

**Comment by avitova** [comment]
I will need the import and export endpoints from content sources on frontend. Let's merge if it's possible.

**Review by avitova — APPROVED** [review]

**Comment by ezr-ondrej** [comment]
I'll try to convince the CI (by trying to restart).

**Comment by ezr-ondrej** [comment]
:rocket: :shipit:

**Pull request merged**
