### PR TITLE
API: make openapi spec endpoint public with a tag filter (HMS-1220)

### PR DESCRIPTION
**Pull request by schuellerf**
Makes openapi.json public

Also introduces routes without authentication in general

Alternate version for #1063

### CODE REVIEW

**Comment by schuellerf** [comment]
This version now serves on both endpoints where `/openapi.json` might be concidered "the current version"
If there would be a `/v2` the `/v1` version would still be at `/api/image-builder/v1/openapi.json`

**Review by croissanne — APPROVED** [review]
thank you! I think this is much more straightforward.

**Review by ezr-ondrej — APPROVED** [review]
Perfect, it looks quite clean now! :+1:

**Comment by ezr-ondrej** [comment]
Also I :orange_heart:  the makefile additions :+1:

**Comment by lzap** [comment]
Sorry I did not follow up on my comments, was on PTO. Great work.

**Pull request merged**
