### PR TITLE
HACKING: Fix reference to developer guide

### PR DESCRIPTION
**Pull request by bcl**

### CODE REVIEW

**Review by lzap — APPROVED** [review]
Thanks.

**Comment by lzap** [comment]
Ah I cannot merge a PR with failed tests. Someone else might be able to.

**Comment by lzap** [comment]
Content sources in ephemeral seem broken.

**Comment by lzap** [comment]
```
    handler_blueprints_test.go:43: 
        	Error Trace:	/home/runner/work/image-builder/image-builder/internal/v1/handler_blueprints_test.go:43
        	Error:      	Received unexpected error:
        	            	command /usr/bin/podman [exec image_builder_test_1709110332 psql -U postgres -c CREATE DATABASE testab012e5b6d9741a3ba2a9d69f33cbdd3;] error: exit status 2, output: psql: error: could not connect to server: No such file or directory
        	            		Is the server running locally and accepting
        	            		connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
```

Random problem?

**Comment by ezr-ondrej** [comment]
> Random problem?

Looks like it, second run went well... I'm up for merging this even if pipeline disagrees, but I'd love to get it bit more stable :/

**Review by ochosi — APPROVED** [review]
LGTM!

**Pull request merged**
