### PR TITLE
internal/v1: return empty array instead of null for collections

### PR DESCRIPTION
**Pull request by croissanne**
HMSIB-173

### CODE REVIEW

**Review by ondrejbudai — COMMENTED** [review]
Maybe cover it with a tiny test? Otherwise LGTM. ;)

**Comment by croissanne** [comment]
> Maybe cover it with a tiny test? Otherwise LGTM. ;)

indeed, I was testing out the jira integration

**Comment by ondrejbudai** [comment]
hehe, sorry, I was too quick

**Review by ondrejbudai — APPROVED** [review]
lgtm, thanks!

**Pull request merged**
