### PR TITLE
🚄 Speed up container build

### PR DESCRIPTION
**Pull request by major**
Use the go-toolset ubi8 container to speed up the container build
process since it comes with golang right out of the box.

### CODE REVIEW

**Comment by major** [comment]
Looks like about 40s including pulls in GitHub Actions. Not bad.

**Comment by teg** [comment]
What's the difference between the golang container and the UBI? Is it just that it already contains the compiler, or does it have a different base too?

**Comment by larskarlitski** [comment]
Is the speed worth it? Go 1.13 on debian might be differently configured from the one in RHEL.

**Comment by larskarlitski** [comment]
> Debian?

:stuck_out_tongue: 

```
$ podman run -it --rm docker.io/library/golang:1.13 
root@24a9d897d838:/go# cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
[...]
```

**Comment by major** [comment]
@teg @larskarlitski I discovered the `ubi8/go-toolset` container and used it instead. Just updated the PR.

**Comment by major** [comment]
Still about 40-45 seconds to build including the pulls.

**Review by Gundersanne — APPROVED** [review]
lgtm :)

**Pull request merged**
