### PR TITLE
test: disable repository tests

### PR DESCRIPTION
**Pull request by ezr-ondrej**
Disable custom repositories tests.

### CODE REVIEW

**Comment by lzap** [comment]
Any idea?

**Comment by ezr-ondrej** [comment]
> Any idea?

Sorry for not updating here, the arm64 worker was down, so naturaly the arm test fails, it seems aws was out of instances, let me recheck.

**Comment by ezr-ondrej** [comment]
The worker seems to be up, lets test! :sunglasses:

**Review by croissanne — APPROVED** [review]

**Pull request merged**
