### PR TITLE
server: Only require Region and ShareWithAccounts for aws upload

### PR DESCRIPTION
**Pull request by Gundersanne**
Secrets should be accessible by image-builder, and added to the request
for composer. The user should only have to give their aws account id to
share the image with.

Region for now should be filled by image-builder as well.

### CODE REVIEW

**Review by teg — DISMISSED** [review]
Nice!  Only one question: How come region is still required if it is filled in by image-builder?

**Comment by teg** [comment]
(My question can be addressed in a follow-up, feel free to merge).

**Comment by Gundersanne** [comment]
@teg i just removed it now :)

**Review by larskarlitski — APPROVED** [review]
Looks good to me. Thank you!

**Review by teg — COMMENTED** [review]
🥳

**Pull request merged**
