### PR TITLE
floorist: Add openscap and snapshot customizations

### PR DESCRIPTION
**Pull request by ochosi**
Adding two customizations we will want to track in the metrics reports - a quick sanity check would be great!

### CODE REVIEW

**Review by achilleas-k — APPROVED** [review]

**Comment by ezr-ondrej** [comment]
The aarch workers seems to be down :)

**Review by lzap — APPROVED** [review]
I don’t like open source projects with bot-dictatorship. :-)

This is a merge, you guys don’t have tests for floorist, do you? :-)

_Live dangerously!_

**Comment by ezr-ondrej** [comment]
You've got yourself an IOW beer @croissanne ! :stuck_out_tongue:

**Pull request merged**
