### PR TITLE
test: disable repository tests

### PR DESCRIPTION
**Pull request by lzap**
Disables repo tests.

### CODE REVIEW

**Review by croissanne — APPROVED** [review]

**Review by croissanne — APPROVED** [review]

**Comment by lzap** [comment]
Is that relevant?

```
10:54:15 2024-01-29 09:54:15 [    INFO] [          MainThread] some resources failed to become ready: clowdjobinvocation/create-contentsources-user
10:54:16 2024-01-29 09:54:16 [   ERROR] [          MainThread] hit timeout error: Could not do 'wait for all deployed resources to be ready' at /var/lib/jenkins/workspace/osbuild-image-builder-pr-check/.bonfire_venv/lib64/python3.6/site-packages/bonfire/openshift.py:85 in time
10:54:16 2024-01-29 09:54:16 [    INFO] [          MainThread] deploy failed: Could not do 'wait for all deployed resources to be ready' at /var/lib/jenkins/workspace/osbuild-image-builder-pr-check/.bonfire_venv/lib64/python3.6/site-packages/bonfire/openshift.py:85 in time
10:54:16 ERROR: deploy failed: Could not do 'wait for all deployed resources to be ready' at /var/lib/jenkins/workspace/osbuild-image-builder-pr-check/.bonfire_venv/lib64/python3.6/site-packages/bonfire/openshift.py:85 in time
```

**Comment by ezr-ondrej** [comment]
I'm taking a stub at it: #1026

**Comment by ezr-ondrej** [comment]
Not needed anymore :)

**Comment by lzap** [comment]
Thank you very much for looking into this.

**Pull request closed without merging**
