### PR TITLE
distributions: add centos stream 8 support

### PR DESCRIPTION
**Pull request by ondrejbudai**
The only question is: Should we use the `mirrorlist`? It's the official way to consume CentOS repos but if get unlucky, we can have a lot of failed builds... Maybe we should just choose one mirror and pin it for now?

### CODE REVIEW

**Comment by teg** [comment]
Let's start out with the official one, and then see what we do if that does not work out?

**Review by teg — APPROVED** [review]
So cool! Thanks!

**Comment by ondrejbudai** [comment]
Please don't merge it yet. I need to update composer in Schutzbot. ;)

**Comment by ondrejbudai** [comment]
Ah, Sanne already updated composer in `main`, so rebase was everything I needed. This is now ready to go in!

**Review by Gundersanne — APPROVED** [review]

**Pull request merged**
