### PR TITLE
tests/ci: fix sonarqube analysis for main branch + ci runners update

### PR DESCRIPTION
**Pull request by jrusz**
Only use the branch options if it's actually running in a branch and
analyse main without them, sonarqube otherwise doesn't recognize the
main branch.

### CODE REVIEW

**Comment by jrusz** [comment]
@Gundersanne could you review this please? It's passing in Gitlab CI, idk why the tests here are failing, I didn't do any change in the code...

**Comment by Gundersanne** [comment]
> @Gundersanne could you review this please? It's passing in Gitlab CI, idk why the tests here are failing, I didn't do any change in the code...

tools/prepare-source.sh downloads the latest spec from composer to make sure it works against stage. So just commit the changes from prepare-source.

**Comment by Gundersanne** [comment]
Ah the latest spec update will require some code changes here. I'll get on those.

**Comment by Gundersanne** [comment]
https://github.com/osbuild/image-builder/pull/319 opened

**Comment by jrusz** [comment]
There are some traceback during Azure cleanup.

**Comment by jrusz** [comment]
Ok apparently it's just trying too hard to delete everything and fails when trying to delete something already deleted :sweat_smile: but that's ok. Can you review please @Gundersanne ? I've also switched to the new Openstack rhos-01 cloud, so open PRs will need rebase otherwise they won't be able to run the ostree tests.

**Review by Gundersanne — APPROVED** [review]

**Pull request merged**
