### PR TITLE
add test case for edge iso image

### PR DESCRIPTION
**Pull request by yih-redhat**
This pr contains:

Test edge installer iso image, includes:
- call rest api to generate iso image, 
- use mkksiso to put ks file into iso, 
- install edge with iso file
- run ansible scirpt to check edge vm.

### CODE REVIEW

**Comment by yih-redhat** [comment]
CI runners has been changed to subscribed image, see #217. The gitlab CI job of this pull request will fail until #217 passed.

**Review by teg — DISMISSED** [review]
Thanks for this! Looking great, exactly what we need :)

**Review by Gundersanne — APPROVED** [review]
thanks! I'll wait for tests to be green and merge :)

**Comment by Gundersanne** [comment]
This is really not ideal 
image

I've retried the test a couple of times now and it seems really flaky, and hard to debug because the log output. I'll retry a few more times but this really should be fixed, so if we merge this an issue should be created and followed up on.

**Comment by yih-redhat** [comment]
> This is really not ideal
> image
> 
> I've retried the test a couple of times now and it seems really flaky, and hard to debug because of the log output. I'll retry a few more times but this really should be fixed, so if we merge this an issue should be created and followed up on.

Hi Sanne,

I have seen this several times before, the root reason is that my test script contains a step to display the metadata of image, which produces lots of log.
I have disabled that step, until we can increase the log size of CI job. Now we can check the failures if job failed.

Pushed and trigger the test again.


Thanks,
Yi

**Comment by ondrejbudai** [comment]
If you need to store bigger logs, just use Gitlab's artifacts: https://docs.gitlab.com/ee/ci/pipelines/job_artifacts.html

**Comment by yih-redhat** [comment]
@Gundersanne Can you please help to merge this pr?

**Comment by yih-redhat** [comment]
> If you need to store bigger logs, just use Gitlab's artifacts: https://docs.gitlab.com/ee/ci/pipelines/job_artifacts.html

Thanks, Ondrej. I will try it later.

**Review by Gundersanne — APPROVED** [review]

**Pull request merged**
