### PR TITLE
floorplan: cast uuid type to string

### PR DESCRIPTION
**Pull request by avitova**
UUID's are not compatible with data frames. This should help.

### CODE REVIEW

**Review by lzap — APPROVED** [review]

**Comment by lzap** [comment]
/retest

I think with this stability of tests, enforcing green tests for trivial PRs is not the best policy.

**Review by ezr-ondrej — APPROVED** [review]
Thank you @avitova :orange_heart:

**Comment by ezr-ondrej** [comment]
Ugh :( shutzbot is fine now, let's root for iqe xD

**Comment by avitova** [comment]
Thanks!

**Pull request merged**
