### PR TITLE
build(deps): upgrade to Go 1.22

### PR DESCRIPTION
**Pull request by lzap**
Upgrading to UBI9 Go 1.22 starting top to bottom (IB first, composer then, images library last).

### CODE REVIEW

**Comment by ezr-ondrej** [comment]
gosec will need a go bump too

**Comment by lzap** [comment]
Bumped gosec, containerfile is set to `latest` so no update is needed until it is released.

**Comment by lzap** [comment]
For the record, it is failing because our CI pulls from a mirror or something. Not sure, let`s try to rebase after it is fully published. It hasn’t been announced yet.

**Comment by croissanne** [comment]
Hmm, the latest go toolset container is still 1.21?

```
sanne@worky ~ $ sudo podman run -it registry.access.redhat.com/ubi9/go-toolset:latest  bash
bash-5.1$ go version
go version go1.21.10 (Red Hat 1.21.10-1.el9_4) linux/amd64
```

I suppose it didn't get updated to 9.5 yet.

**Comment by lzap** [comment]
Aaaand it is up:

```
$ go version
go version go1.22.7 (Red Hat 1.22.7-2.el9_5) linux/amd64
```

Rebased.

**Review by ezr-ondrej — APPROVED** [review]
Nice! :orange_heart:

**Pull request merged**
