### PR TITLE
v1: include compose_id in clone response

### PR DESCRIPTION
**Pull request by ezr-ondrej**
Clones should include their parent ID, to easily match them.
This follows rest standards.

I've got no idea how to do this properly, but I just felt it would be really nice to have compose_id in the clone detail response :thinking:

### CODE REVIEW

**Review by croissanne — DISMISSED** [review]
lgtm

**Review by croissanne — DISMISSED** [review]
thanks!

**Comment by ezr-ondrej** [comment]
:green_apple: :tada:

**Comment by croissanne** [comment]
@ezr-ondrej ugh I didn't press the button ._. can you rebase, happy to ack again

**Comment by ezr-ondrej** [comment]
Sure :) here it goes! :)

**Comment by ezr-ondrej** [comment]
:green_apple: :tada:

**Pull request merged**
