### PR TITLE
v1: Enable rhel-edge-container

### PR DESCRIPTION
**Pull request by Gundersanne**
- [x] https://github.com/osbuild/osbuild-composer/pull/2035

### CODE REVIEW

**Review by achilleas-k — APPROVED** [review]

**Review by achilleas-k — CHANGES_REQUESTED** [review]
Do we also need to add `edge-container` and `rhel-edge-container` to the list of image types for the S3 upload target?
https://github.com/osbuild/image-builder/blob/31e47e202eca0dee785b9c422bd6bf8f0fb17223/internal/v1/server.go#L519-L540

**Review by teg — COMMENTED** [review]
Hmm... Does the edge team want these containers? I thought they only wanted the simplified installer?

**Comment by Gundersanne** [comment]
> Hmm... Does the edge team want these containers? I thought they only wanted the simplified installer?

I'm not sure actually, @achilleas-k  do you remember? I'll open a PR in the meantime with the extra types for rhel-8.5 because those are important (and unrelated).

**Comment by achilleas-k** [comment]
> > Hmm... Does the edge team want these containers? I thought they only wanted the simplified installer?
> 
> I'm not sure actually, @achilleas-k do you remember? I'll open a PR in the meantime with the extra types for rhel-8.5 because those are important (and unrelated).

I don't remember if they asked for them either.  I think we decided to add it anyway since it's an image we build and it's useful.  The general plan is to add every image type to the backend eventually, isn't it?

**Comment by teg** [comment]
I think I may have been the source of the confusion :-/

**Comment by Gundersanne** [comment]
rhel-edge-container is

**Pull request closed without merging**
