### PR TITLE
Enable testing in pr_check.sh

### PR DESCRIPTION
**Pull request by jrusz**

### CODE REVIEW

**Review by atodorov — COMMENTED** [review]
@jrusz who is supposed to trigger this script? Don't we need it executed from some of the other CI jobs  ?

**Comment by jrusz** [comment]
> @jrusz who is supposed to trigger this script? Don't we need it executed from some of the other CI jobs ?

I think it's being executed by the @app-sre-bot you can see the status reported on this PR as `ci.ext.devshift.net PR build`

**Comment by atodorov** [comment]
> you can see the status reported on this PR as `ci.ext.devshift.net PR build`

I totally didn't pay attention to this. Naming things is hard! Tests look good though.

**Pull request merged**
