### PR TITLE
v1: take snapshot repository name from the repo response (HMS-4784)

### PR DESCRIPTION
**Pull request by croissanne**
The repository name in snapshot reponses is empty, so just take it from the repositories response.

### CODE REVIEW

**Review by lzap — APPROVED** [review]

**Review by lzap — APPROVED** [review]

**Comment by lucasgarfield** [comment]
Nice workaround! But _should_ the repository name in the snapshots response be empty? Should we raise an issue with the Repositories team, @croissanne?

**Comment by croissanne** [comment]
> Nice workaround! But _should_ the repository name in the snapshots response be empty? Should we raise an issue with the Repositories team, @croissanne?

I guess it shouldn't no, @jlsherrill fyi.

**Pull request merged**
