### PR TITLE
build(deps): update deps manually

### PR DESCRIPTION
**Pull request by lzap**
SSIA

Bot is failing with this trying out manually: https://github.com/osbuild/image-builder/pull/1300

### CODE REVIEW

**Comment by lzap** [comment]
Unlucky it was green but nobody merged.

**Comment by ezr-ondrej** [comment]
And it's not anymore? :(

**Comment by lzap** [comment]
Tests do fail me now. I will try again later.

**Comment by lzap** [comment]
Let’s try it again.

**Comment by lzap** [comment]
https://github.com/osbuild/image-builder/pull/1311

**Pull request closed without merging**
