### PR TITLE
v1: rename to blueprints

### PR DESCRIPTION
**Pull request by lzap**
Although there is a precedent in using both plural and singular forms (composes/compose), I believe it is worth to be consistent.

The API is still experimental, so this patch is fine.

### CODE REVIEW

**Review by ezr-ondrej — APPROVED** [review]
Yup, from what @croissanne said I understand this is what we want, so lets get it in sooner rather then later :)

**Review by ezr-ondrej — CHANGES_REQUESTED** [review]
Tests needs updating (we use the path in tests)

**Comment by lzap** [comment]
Damn I missed these strings somehow.

**Review by ezr-ondrej — APPROVED** [review]
Only renames experimental enpoints, looks safe, thanks @lzap ! :+1:

**Comment by ezr-ondrej** [comment]
:green_apple: :tada:

**Pull request merged**
