### PR TITLE
v1/api: drop Blueprints experimental endpoints (HMS-4200)

### PR DESCRIPTION
**Pull request by ezr-ondrej**
Follow-up for #1203 to clean-up once we fully migrate IQE and frontend :)
Frontend done: https://github.com/osbuild/image-builder-frontend/pull/2134

### CODE REVIEW

**Comment by ezr-ondrej** [comment]
@jrusz this would remove blueprints from `/experimental` we are ready in the frontend, meaning ready whenever you are :)

**Review by lzap — DISMISSED** [review]

**Comment by jrusz** [comment]
Looks like this feel through the cracks :sweat_smile: This is still relevant, right? I probably don't have a ticket for this created so I'll create one to update our test api endpoints.

**Comment by ezr-ondrej** [comment]
Yeah, it's not a high prio, but would be nice to get in :)

**Review by jrusz — APPROVED** [review]
Since all tests are passing I think it's fine :)

**Comment by lzap** [comment]
I wonder if this has anything to do with: https://github.com/RHEnVision/provisioning-backend/pull/806

**Comment by ezr-ondrej** [comment]
> I wonder if this has anything to do with: [RHEnVision/provisioning-backend#806](https://github.com/RHEnVision/provisioning-backend/pull/806)

Might be, but this should rather Improve it in my mind. :thinking:

**Pull request merged**
