### PR TITLE
Migrate to GitLab CI

### PR DESCRIPTION
**Pull request by atodorov**

### CODE REVIEW

**Comment by atodorov** [comment]
@Gundersanne, @yuxisun1217 the tests are showing what seems to be an error but I can't understand why it happens:
https://gitlab.com/osbuild/ci/image-builder/-/jobs/1318846366

```
+ Test_postToComposer
++ curl -w '%{http_code}' -H 'x-rh-identity: eyJlbnRpdGxlbWVudHMiOnsiaW5zaWdodHMiOnsiaXNfZW50aXRsZWQiOnRydWV9LCJzbWFydF9tYW5hZ2VtZW50Ijp7ImlzX2VudGl0bGVkIjp0cnVlfSwib3BlbnNoaWZ0Ijp7ImlzX2VudGl0bGVkIjp0cnVlfSwiaHlicmlkIjp7ImlzX2VudGl0bGVkIjp0cnVlfSwibWlncmF0aW9ucyI6eyJpc19lbnRpdGxlZCI6dHJ1ZX0sImFuc2libGUiOnsiaXNfZW50aXRsZWQiOnRydWV9fSwiaWRlbnRpdHkiOnsiYWNjb3VudF9udW1iZXIiOiIwMDAwMDAiLCJ0eXBlIjoiVXNlciIsInVzZXIiOnsidXNlcm5hbWUiOiJ1c2VyIiwiZW1haWwiOiJ1c2VyQHVzZXIudXNlciIsImZpcnN0X25hbWUiOiJ1c2VyIiwibGFzdF9uYW1lIjoidXNlciIsImlzX2FjdGl2ZSI6dHJ1ZSwiaXNfb3JnX2FkbWluIjp0cnVlLCJpc19pbnRlcm5hbCI6dHJ1ZSwibG9jYWxlIjoiZW4tVVMifSwiaW50ZXJuYWwiOnsib3JnX2lkIjoiMDAwMDAwIn19fQ==' -H 'Content-Type: application/json' --request POST --data @/tmp/tmp.qratkgFpbe/request.json http://localhost:8086/api/image-builder/v1.0/compose
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   662  100   151  100   511   147k   499k --:--:-- --:--:-- --:--:--  646k
+ RESULT='{"errors":[{"detail":"request body has an error: failed to decode request body: invalid character '\'','\'' looking for beginning of value","title":"400"}]}
400'
++ getExitCode '{"errors":[{"detail":"request body has an error: failed to decode request body: invalid character '\'','\'' looking for beginning of value","title":"400"}]}
400'
++ read -r -d '' -a ARR
++ echo 400
+ EXIT_CODE=400
+ [[ 400 == 201 ]]
```

This is a clear mismatch in the expected result but previous lines in this log show that things were working well. 

A secondary issue is that I see api.sh continuing afterwards instead of exiting with non-zero.

**Comment by yuxisun1217** [comment]
"A secondary issue is that I see api.sh continuing afterwards instead of exiting with non-zero." I think it's as expected because the following steps are to clean up the cloud resources. There's a "trap cleanup EXIT". I don't know much about trap but it seems like to catch the exit signal and run the cleanup function.

**Comment by Gundersanne** [comment]
> @Gundersanne, @yuxisun1217 the tests are showing what seems to be an error but I can't understand why it happens:
> https://gitlab.com/osbuild/ci/image-builder/-/jobs/1318846366
> 
> ```
> + Test_postToComposer
> ++ curl -w '%{http_code}' -H 'x-rh-identity: eyJlbnRpdGxlbWVudHMiOnsiaW5zaWdodHMiOnsiaXNfZW50aXRsZWQiOnRydWV9LCJzbWFydF9tYW5hZ2VtZW50Ijp7ImlzX2VudGl0bGVkIjp0cnVlfSwib3BlbnNoaWZ0Ijp7ImlzX2VudGl0bGVkIjp0cnVlfSwiaHlicmlkIjp7ImlzX2VudGl0bGVkIjp0cnVlfSwibWlncmF0aW9ucyI6eyJpc19lbnRpdGxlZCI6dHJ1ZX0sImFuc2libGUiOnsiaXNfZW50aXRsZWQiOnRydWV9fSwiaWRlbnRpdHkiOnsiYWNjb3VudF9udW1iZXIiOiIwMDAwMDAiLCJ0eXBlIjoiVXNlciIsInVzZXIiOnsidXNlcm5hbWUiOiJ1c2VyIiwiZW1haWwiOiJ1c2VyQHVzZXIudXNlciIsImZpcnN0X25hbWUiOiJ1c2VyIiwibGFzdF9uYW1lIjoidXNlciIsImlzX2FjdGl2ZSI6dHJ1ZSwiaXNfb3JnX2FkbWluIjp0cnVlLCJpc19pbnRlcm5hbCI6dHJ1ZSwibG9jYWxlIjoiZW4tVVMifSwiaW50ZXJuYWwiOnsib3JnX2lkIjoiMDAwMDAwIn19fQ==' -H 'Content-Type: application/json' --request POST --data @/tmp/tmp.qratkgFpbe/request.json http://localhost:8086/api/image-builder/v1.0/compose
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
> 100   662  100   151  100   511   147k   499k --:--:-- --:--:-- --:--:--  646k
> + RESULT='{"errors":[{"detail":"request body has an error: failed to decode request body: invalid character '\'','\'' looking for beginning of value","title":"400"}]}
> 400'
> ++ getExitCode '{"errors":[{"detail":"request body has an error: failed to decode request body: invalid character '\'','\'' looking for beginning of value","title":"400"}]}
> 400'
> ++ read -r -d '' -a ARR
> ++ echo 400
> + EXIT_CODE=400
> + [[ 400 == 201 ]]
> ```
> 
> This is a clear mismatch in the expected result but previous lines in this log show that things were working well.
> 
> A secondary issue is that I see api.sh continuing afterwards instead of exiting with non-zero.

Hmm could you dump the request before you send it? 

---

Also the gcp test seems to have failed with `ERROR: No key found in /etc/pki/entitlement directory.  It means this machine is not subscribed.`

And the azure test has env vars missing

**Review by Gundersanne — APPROVED** [review]
Nice :)

**Pull request merged**
