### PR TITLE
api: gcp upload doesn't require an account

### PR DESCRIPTION
**Pull request by lavocatt**
As required by https://issues.redhat.com/browse/HMS-2352, uploading to GCP doesn't necessitate an account to share the image to. In that case, the image is only launchable.

Composer was already supporting the functionality, this commit just makes image builder compliant with it.

### CODE REVIEW

**Comment by lavocatt** [comment]
This should solve https://github.com/osbuild/image-builder/issues/829, but I need a way to test it on my local machine.

**Review by croissanne — APPROVED** [review]

**Comment by lavocatt** [comment]
Alright, the local tests proved to be successful!

Composing this request:
```
{
  "distribution": "centos-8",
  "image_requests": [
    {
      "architecture": "x86_64",
      "image_type": "gcp",
      "upload_request": {
        "type": "gcp",
        "options":{
        }
      }
    }
  ]
}
```

Returned:
```
curl -H "Content-Type: application/json" -H "x-rh-identity: eyJlbnRpdGxlbWVudHMiOnsicmhlbCI6eyJpc19lbnRpdGxlZCI6dHJ1ZX0sImluc2lnaHRzIjp7ImlzX2VudGl0bGVkIjp0cnVlfSwic21hcnRfbWFuYWdlbWVudCI6eyJpc19lbnRpdGxlZCI6dHJ1ZX0sIm9wZW5zaGlmdCI6eyJpc19lbnRpdGxlZCI6dHJ1ZX0sImh5YnJpZCI6eyJpc19lbnRpdGxlZCI6dHJ1ZX0sIm1pZ3JhdGlvbnMiOnsiaXNfZW50aXRsZWQiOnRydWV9LCJhbnNpYmxlIjp7ImlzX2VudGl0bGVkIjp0cnVlfX0sImlkZW50aXR5Ijp7ImFjY291bnRfbnVtYmVyIjoiMDAwMDAwIiwidHlwZSI6IlVzZXIiLCJ1c2VyIjp7InVzZXJuYW1lIjoidXNlciIsImVtYWlsIjoidXNlckB1c2VyLnVzZXIiLCJmaXJzdF9uYW1lIjoidXNlciIsImxhc3RfbmFtZSI6InVzZXIiLCJpc19hY3RpdmUiOnRydWUsImlzX29yZ19hZG1pbiI6dHJ1ZSwiaXNfaW50ZXJuYWwiOnRydWUsImxvY2FsZSI6ImVuLVVTIn0sImludGVybmFsIjp7Im9yZ19pZCI6IjAwMDAwMCJ9fX0K" http://localhost:8086/api/image-builder/v1/composes/c6a4dbbd-1387-4850-be54-c8f57bf061e4
{"image_status":{"status":"success","upload_status":{"options":{"image_name":"composer-api-c0c75888-b0f9-4b1b-b21c-e82584ffb151","project_id":"red-hat-image-builder"},"status":"success","type":"gcp"}},"request":{"distribution":"centos-8","image_requests":[{"architecture":"x86_64","image_type":"gcp","upload_request":{"options":{},"type":"gcp"}}]}}
```

**Review by croissanne — APPROVED** [review]
lgtm!

**Comment by lavocatt** [comment]
Alright, so I think the frontend pr is not sending an empty option object to share, but instead `"options":{"share_with_accounts":["user:undefined"]}` which means that we get this error actually:

`{"image_status":{"error":{"details":"org.osbuild.gcp","id":3,"reason":"failed to set new image policy: googleapi: Error 400: Principal undefined is of type \"group\". The principal should appear as \"group:undefined\". See https://cloud.google.com/iam/help/members/types for additional documentation."},"status":"failure","upload_status":{"options":{"image_name":"","project_id":""},"status":"failure","type":"gcp"}},"request":{"customizations":{},"distribution":"rhel-92","image_name":"adi","image_requests":[{"architecture":"x86_64","image_type":"gcp","upload_request":{"options":{"share_with_accounts":["user:undefined"]},"type":"gcp"}}]}}`

So I don't know what should be best here:
* make the fronted send an empty option object
* make the frontend send `group:undefined` instead of `user:undefined`
* make the backend treat `user:undefined` as a nil string when forwarding that to composer

what's your opinion ?

**Pull request merged**
