### PR TITLE
Filter errors

### PR DESCRIPTION
**Pull request by Gundersanne**

### CODE REVIEW

**Comment by teg** [comment]
Might want to run the "open a support case" advice by CEE.

**Comment by Gundersanne** [comment]
> Might want to run the "open a support case" advice by CEE.

Yea probably need a different string there, can also say unknown or something.

**Comment by teg** [comment]
I like the idea though. Should just get their ack and make sure we agree on what info to include (and when to give this advice, probably should not be on a catch all)

**Comment by Gundersanne** [comment]
> I like the idea though. Should just get their ack and make sure we agree on what info to include (and when to give this advice, probably should not be on a catch all)

Yea, I'm just wondering what the default error should be.

**Pull request closed without merging**
