### PR TITLE
db: fix bluperint unique name migration

### PR DESCRIPTION
**Pull request by ezr-ondrej**

### CODE REVIEW

**Comment by lzap** [comment]
So I am assuming the migration did not come through, so we can update existing one. Good.

I suggest to add a comment explaining what happens:

```
-- Add " N" suffix to all blueprint names which row number is higher
-- than 2. For two blueprints named "test" it will leave one record as
-- "test" and the other will be updated to "test 2" and so on. The 
-- order is picked at random.
```

**Review by lzap — DISMISSED** [review]
I tested this on my laptop:

```
imagebuilder=# insert into blueprints values (gen_random_uuid(), '1', '1', 'xxx', '');
INSERT 0 1
imagebuilder=# insert into blueprints values (gen_random_uuid(), '1', '1', 'xxx', '');
INSERT 0 1
imagebuilder=# insert into blueprints values (gen_random_uuid(), '1', '1', 'xxx', '');
INSERT 0 1
imagebuilder=# select * from blueprints;
┌──────────────────────────────────────┬────────┬────────────────┬────────┬─────────────┬────────────────────────────┐
│                  id                  │ org_id │ account_number │  name  │ description │         created_at         │
├──────────────────────────────────────┼────────┼────────────────┼────────┼─────────────┼────────────────────────────┤
│ b8a7dfc1-0dc9-4a6e-b41f-7d6ada01a495 │ 1      │ 1              │ test   │             │ 2024-04-03 13:59:03.296763 │
│ 4bdf66b3-af74-4877-ac78-5b849b5f6d12 │ 1      │ 1              │ test2  │             │ 2024-04-03 14:03:35.91646  │
│ 10c4c172-191e-4b24-8df2-b8a637eb98c5 │ 1      │ 1              │ test3  │             │ 2024-04-03 14:03:39.077358 │
│ 6eee04d9-c680-4d2d-91f2-83e140c67e6a │ 1      │ 1              │ test 2 │             │ 2024-04-03 14:00:19.420983 │
│ c976a584-fbb1-401d-8295-efef0c404b38 │ 1      │ 1              │ test 3 │             │ 2024-04-03 14:00:19.839978 │
│ a810ad11-bd9d-46ef-9c8c-c68eeab2180d │ 1      │ 1              │ test 4 │             │ 2024-04-03 14:00:20.119022 │
│ daffc0be-7a48-4254-b20e-5305fb1830aa │ 1      │ 1              │ xxx    │             │ 2024-04-03 14:18:42.305871 │
│ 6474a4b4-2c83-4deb-9d2d-30c94ae1fb5f │ 1      │ 1              │ xxx    │             │ 2024-04-03 14:18:43.128118 │
│ 37f0228c-b564-40cd-baf6-175f60cee19b │ 1      │ 1              │ xxx    │             │ 2024-04-03 14:18:43.545909 │
└──────────────────────────────────────┴────────┴────────────────┴────────┴─────────────┴────────────────────────────┘
(9 řádek)

imagebuilder=# update blueprints set name = concat(u.name, ' ', u.rn) from (select * from (select id, name, row_number() over (partition by name) as rn from blueprints) fu where fu.rn > 1) u where blueprints.id = u.id;
UPDATE 2
imagebuilder=# update blueprints set name = concat(u.name, ' ', u.rn) from (select * from (select id, name, row_number() over (partition by name) as rn from blueprints) fu where fu.rn > 1) u where blueprints.id = u.id;
UPDATE 0
imagebuilder=# select * from blueprints;
┌──────────────────────────────────────┬────────┬────────────────┬────────┬─────────────┬────────────────────────────┐
│                  id                  │ org_id │ account_number │  name  │ description │         created_at         │
├──────────────────────────────────────┼────────┼────────────────┼────────┼─────────────┼────────────────────────────┤
│ b8a7dfc1-0dc9-4a6e-b41f-7d6ada01a495 │ 1      │ 1              │ test   │             │ 2024-04-03 13:59:03.296763 │
│ 4bdf66b3-af74-4877-ac78-5b849b5f6d12 │ 1      │ 1              │ test2  │             │ 2024-04-03 14:03:35.91646  │
│ 10c4c172-191e-4b24-8df2-b8a637eb98c5 │ 1      │ 1              │ test3  │             │ 2024-04-03 14:03:39.077358 │
│ 6eee04d9-c680-4d2d-91f2-83e140c67e6a │ 1      │ 1              │ test 2 │             │ 2024-04-03 14:00:19.420983 │
│ c976a584-fbb1-401d-8295-efef0c404b38 │ 1      │ 1              │ test 3 │             │ 2024-04-03 14:00:19.839978 │
│ a810ad11-bd9d-46ef-9c8c-c68eeab2180d │ 1      │ 1              │ test 4 │             │ 2024-04-03 14:00:20.119022 │
│ daffc0be-7a48-4254-b20e-5305fb1830aa │ 1      │ 1              │ xxx    │             │ 2024-04-03 14:18:42.305871 │
│ 6474a4b4-2c83-4deb-9d2d-30c94ae1fb5f │ 1      │ 1              │ xxx 2  │             │ 2024-04-03 14:18:43.128118 │
│ 37f0228c-b564-40cd-baf6-175f60cee19b │ 1      │ 1              │ xxx 3  │             │ 2024-04-03 14:18:43.545909 │
└──────────────────────────────────────┴────────┴────────────────┴────────┴─────────────┴────────────────────────────┘
(9 řádek)
```

**Review by croissanne — APPROVED** [review]
lgtm! thanks!

**Review by ezr-ondrej — COMMENTED** [review]
We need to do it cross org :face_in_clouds:

**Comment by ezr-ondrej** [comment]
It was easy - just partitioning by org_id as well did the trick

**Review by croissanne — DISMISSED** [review]

**Comment by lzap** [comment]
Does not work as expected.

**Review by lzap — CHANGES_REQUESTED** [review]
Window functions cannot be used with multiple columns, it does not work like grouping. Let me find a different solution, we can either use grouping but row numbering will not be available or I have an idea.

**Comment by ezr-ondrej** [comment]
```
temp_blueprint=# SELECT * FROM blueprints;
                  id                  |         name          | org_id |         created_at         
--------------------------------------+-----------------------+--------+----------------------------
 b258589a-880d-492e-9864-a0f3b4481023 | Blueprint name        | 1      | 2024-04-03 18:42:36.369445
 39e300c2-36bf-46df-84ca-cb9c89b83932 | Blueprint name        | 1      | 2024-04-03 18:42:36.369445
 1f759bb1-d8c2-4f26-9ce2-abf90a92d13e | Blueprint name        | 1      | 2024-04-03 18:42:36.369445
 bd01576c-8638-4006-bdac-654a6e48feec | Blueprint cool        | 1      | 2024-04-03 18:42:36.369445
 325a8685-2520-4fdd-8ff2-97b2b39205a4 | Blueprint cool        | 1      | 2024-04-03 18:42:36.369445
 3e5566f4-f304-4759-9fc9-4571b40f8aa6 | Blueprint cool unique | 1      | 2024-04-03 18:42:36.369445
 1de9be95-3c56-4694-b55f-df66d5b7ed9b | Blueprint cool        | 2      | 2024-04-03 18:42:36.369445
 8dd66e1d-0fa6-4775-b854-5e907c6245bd | Blueprint cool        | 2      | 2024-04-03 18:42:36.369445
 b19afb04-90d9-418f-b88f-fc90511308d1 | Blueprint name        | 2      | 2024-04-03 18:42:36.369445
 5183fef6-2eb0-4dd8-af44-137313944697 | Blueprint name        | 2      | 2024-04-03 18:42:36.369445
(10 rows)

temp_blueprint=# UPDATE blueprints SET name = CONCAT(names.name, ' ', names.rn::text, ' (renamed at ', TO_CHAR(CURRENT_TIMESTAMP, 'YYYY/MM/DD HH24:MM:SS'), ')')
    FROM (SELECT * FROM (select id, name, row_number() over (partition by name, org_id order by created_at) as rn from blueprints) AS rns
    WHERE rns.rn > 1) AS names WHERE blueprints.id = names.id;
UPDATE 5
temp_blueprint=# SELECT * FROM blueprints;
                  id                  |                       name                        | org_id |         created_at         
--------------------------------------+---------------------------------------------------+--------+----------------------------
 b258589a-880d-492e-9864-a0f3b4481023 | Blueprint name                                    | 1      | 2024-04-03 18:42:36.369445
 bd01576c-8638-4006-bdac-654a6e48feec | Blueprint cool                                    | 1      | 2024-04-03 18:42:36.369445
 3e5566f4-f304-4759-9fc9-4571b40f8aa6 | Blueprint cool unique                             | 1      | 2024-04-03 18:42:36.369445
 1de9be95-3c56-4694-b55f-df66d5b7ed9b | Blueprint cool                                    | 2      | 2024-04-03 18:42:36.369445
 b19afb04-90d9-418f-b88f-fc90511308d1 | Blueprint name                                    | 2      | 2024-04-03 18:42:36.369445
 325a8685-2520-4fdd-8ff2-97b2b39205a4 | Blueprint cool 2 (renamed at 2024/04/03 18:04:44) | 1      | 2024-04-03 18:42:36.369445
 8dd66e1d-0fa6-4775-b854-5e907c6245bd | Blueprint cool 2 (renamed at 2024/04/03 18:04:44) | 2      | 2024-04-03 18:42:36.369445
 39e300c2-36bf-46df-84ca-cb9c89b83932 | Blueprint name 2 (renamed at 2024/04/03 18:04:44) | 1      | 2024-04-03 18:42:36.369445
 1f759bb1-d8c2-4f26-9ce2-abf90a92d13e | Blueprint name 3 (renamed at 2024/04/03 18:04:44) | 1      | 2024-04-03 18:42:36.369445
 5183fef6-2eb0-4dd8-af44-137313944697 | Blueprint name 2 (renamed at 2024/04/03 18:04:44) | 2      | 2024-04-03 18:42:36.369445
(10 rows)
```

**Comment by ezr-ondrej** [comment]
```
temp_blueprint=# SELECT * FROM blueprints;
                  id                  |       name       | org_id |         created_at         
--------------------------------------+------------------+--------+----------------------------
 be78769a-abce-46a4-ba4d-70c30d9a782b | Blueprint name   | 1      | 2024-04-03 18:46:36.07728
 051d4fb2-b89d-45bb-b5ce-61ca1d0b6cb0 | Blueprint name   | 1      | 2024-04-03 18:46:37.374068
 5e56600f-50b9-4721-89b5-e32e45202b26 | Blueprint name   | 1      | 2024-04-03 18:46:39.830295
 1fe587ec-ece5-4891-b2ec-cc8589f805c0 | Blueprint cool   | 1      | 2024-04-03 18:46:45.874503
 0a0427cc-4a00-4e0b-a123-5c9e518cd554 | Blueprint cool   | 1      | 2024-04-03 18:46:46.803646
 4eb29ad8-525b-4fde-b755-bac0230001a2 | Blueprint name   | 2      | 2024-04-03 18:46:53.8471
 21530461-9981-4032-bb8b-f40e8aaa32a7 | Blueprint name   | 2      | 2024-04-03 18:46:54.80435
 d4f50450-9471-4cb9-ab7f-7aa61c4c8961 | Blueprint name   | 2      | 2024-04-03 18:46:57.712829
 546911cd-4640-4a2d-8e45-12961568bce3 | Blueprint name   | 2      | 2024-04-03 18:46:58.342171
 b076e0bd-e9f6-4210-9af0-5042f178d4dd | Blueprint name   | 2      | 2024-04-03 18:46:58.93005
 a15471b8-5e43-43f4-80cd-0e1eddbf9b77 | Blueprint unique | 2      | 2024-04-03 18:47:06.938094
 bf0dc923-a7ee-4089-9881-89b1fe3d6b3f | Blueprint unique | 1      | 2024-04-03 18:47:09.808783
(12 rows)

temp_blueprint=# UPDATE blueprints SET name = CONCAT(names.name, ' ', names.rn::text, ' (renamed at ', TO_CHAR(CURRENT_TIMESTAMP, 'YYYY/MM/DD HH24:MM:SS'), ')')
    FROM (SELECT id, name, row_number() over (partition by name, org_id order by created_at) as rn from blueprints) AS names
    WHERE names.rn > 1 AND blueprints.id = names.id;
UPDATE 7
temp_blueprint=# SELECT * FROM blueprints;
                  id                  |                       name                        | org_id |         created_at         
--------------------------------------+---------------------------------------------------+--------+----------------------------
 be78769a-abce-46a4-ba4d-70c30d9a782b | Blueprint name                                    | 1      | 2024-04-03 18:46:36.07728
 1fe587ec-ece5-4891-b2ec-cc8589f805c0 | Blueprint cool                                    | 1      | 2024-04-03 18:46:45.874503
 4eb29ad8-525b-4fde-b755-bac0230001a2 | Blueprint name                                    | 2      | 2024-04-03 18:46:53.8471
 a15471b8-5e43-43f4-80cd-0e1eddbf9b77 | Blueprint unique                                  | 2      | 2024-04-03 18:47:06.938094
 bf0dc923-a7ee-4089-9881-89b1fe3d6b3f | Blueprint unique                                  | 1      | 2024-04-03 18:47:09.808783
 051d4fb2-b89d-45bb-b5ce-61ca1d0b6cb0 | Blueprint name 2 (renamed at 2024/04/03 18:04:36) | 1      | 2024-04-03 18:46:37.374068
 5e56600f-50b9-4721-89b5-e32e45202b26 | Blueprint name 3 (renamed at 2024/04/03 18:04:36) | 1      | 2024-04-03 18:46:39.830295
 0a0427cc-4a00-4e0b-a123-5c9e518cd554 | Blueprint cool 2 (renamed at 2024/04/03 18:04:36) | 1      | 2024-04-03 18:46:46.803646
 21530461-9981-4032-bb8b-f40e8aaa32a7 | Blueprint name 2 (renamed at 2024/04/03 18:04:36) | 2      | 2024-04-03 18:46:54.80435
 d4f50450-9471-4cb9-ab7f-7aa61c4c8961 | Blueprint name 3 (renamed at 2024/04/03 18:04:36) | 2      | 2024-04-03 18:46:57.712829
 546911cd-4640-4a2d-8e45-12961568bce3 | Blueprint name 4 (renamed at 2024/04/03 18:04:36) | 2      | 2024-04-03 18:46:58.342171
 b076e0bd-e9f6-4210-9af0-5042f178d4dd | Blueprint name 5 (renamed at 2024/04/03 18:04:36) | 2      | 2024-04-03 18:46:58.93005
(12 rows)
```

**Review by lzap — DISMISSED** [review]
I take it back, I tested it incorrectly. I already had "Test 2" and it was creating dupes. We agreed to put something unique (date+time) in order to prevent that.

@ezr-ondrej had a concern we might hit limit of the text field, I am pretty sure QA folks have some names that are at the max, so I suggest to extend the limit by 50 characters just to make enough room for that.

**Review by lzap — APPROVED** [review]
All good and tested, thanks.

**Comment by lzap** [comment]
Let’s go and fix stage.

**Pull request merged**
