### PR TITLE
test: Build rhel-85 in the edge test

### PR DESCRIPTION
**Pull request by Gundersanne**

### CODE REVIEW

**Review by teg — DISMISSED** [review]

**Review by teg — DISMISSED** [review]

**Comment by Gundersanne** [comment]
the depsolving here is timing out even with 2 minutes?! :/

**Comment by yih-redhat** [comment]
Hi, @Sanne, I checked the test failure of this pr, downloaded the iso and tried to install it locally.
The iso installation started but didn't finish successfully, here is the error message:

Installing.
Starting pull of rhel/8/x86_64/edge from rhel-edge-commit
================================================================================
================================================================================
Error
   The following error occurred while installing.  This is a fatal error and
   installation will be aborted.
   Failed to pull from repository: g-io-error-quark: opening repo:
   opendir(/ostree/repo): No such file or directory (1)
   
The root reason is that the installer path has changed, in 8.4 it was "/ostree/repo" and in 8.5 it is "/run/install/repo/ostree/repo"

How to fix it:
Just need to update this line https://github.com/osbuild/image-builder/pull/288/files#diff-87f64c1d2903b0fbefd21392e794075a5131d7f4f4e0c865aceeecbbd8160e4cL470 , please replace "--url=file:///ostree/repo" with "--url=file:///run/install/repo/ostree/repo", and it should fix this issue.

You can also take a look of this as reference: https://github.com/osbuild/osbuild-composer/blob/main/test/cases/ostree-ng.sh#L108-L123 , in this code it sets different installer path for 8.4 and 8.5/later.

**Comment by Gundersanne** [comment]
Thank you @yih-redhat , I'll update this PR asap.

**Comment by Sanne** [comment]
wrong "@Sanne" mentioned, but happy to meet you all :)

**Comment by yih-redhat** [comment]
Hi @Gundersanne , what's the status of this pr now? Please let me know if it fail again after you fixed the installer_path issue.

**Review by achilleas-k — APPROVED** [review]

**Pull request merged**
